apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
  namespace: v2ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
        - name: v2ray
          image: v2ray/official:latest
          ports:
            - containerPort: 8001
          resources:
---
apiVersion: v1
kind: Service
metadata:
  name: v2ray
  namespace: v2ray
  labels:
    app: v2ray
spec:
  type: NodePort
  ports:
    - name: v2ray
      port: 8001
      targetPort: 8001
  selector:
    app: v2ray
